export type TableStoryRow = {
  sku: string;
  name: string;
  stock: number;
  fillRate: number;
  status: string;
};

export const tableStoryRows: TableStoryRow[] = [
  { sku: "SKU-1001", name: "Classic Tee", stock: 124, fillRate: 98, status: "Healthy" },
  { sku: "SKU-1002", name: "Relaxed Hoodie", stock: 22, fillRate: 74, status: "Risk" },
  { sku: "SKU-1003", name: "Everyday Pants", stock: 0, fillRate: 52, status: "Out" },
  { sku: "SKU-1004", name: "Canvas Jacket", stock: 64, fillRate: 88, status: "Healthy" },
  { sku: "SKU-1005", name: "Workwear Shirt", stock: 9, fillRate: 69, status: "Risk" },
  { sku: "SKU-1006", name: "City Runner", stock: 48, fillRate: 81, status: "Healthy" },
  { sku: "SKU-1007", name: "Soft Knit", stock: 6, fillRate: 61, status: "Risk" },
  { sku: "SKU-1008", name: "Trail Shorts", stock: 18, fillRate: 77, status: "Risk" },
  { sku: "SKU-1009", name: "Utility Vest", stock: 32, fillRate: 84, status: "Healthy" },
  { sku: "SKU-1010", name: "Quarter Zip", stock: 15, fillRate: 71, status: "Risk" },
  { sku: "SKU-1011", name: "Daily Cap", stock: 140, fillRate: 99, status: "Healthy" },
  { sku: "SKU-1012", name: "Lightweight Parka", stock: 4, fillRate: 55, status: "Out" },
  { sku: "SKU-1013", name: "Wool Beanie", stock: 88, fillRate: 93, status: "Healthy" },
  { sku: "SKU-1014", name: "All-day Socks", stock: 210, fillRate: 97, status: "Healthy" },
  { sku: "SKU-1015", name: "Field Jacket", stock: 27, fillRate: 78, status: "Risk" },
  { sku: "SKU-1016", name: "Rain Shell", stock: 12, fillRate: 68, status: "Risk" },
  { sku: "SKU-1017", name: "Studio Jogger", stock: 44, fillRate: 86, status: "Healthy" },
  { sku: "SKU-1018", name: "Canvas Belt", stock: 96, fillRate: 92, status: "Healthy" },
  { sku: "SKU-1019", name: "Puffer Vest", stock: 8, fillRate: 63, status: "Risk" },
  { sku: "SKU-1020", name: "Thermal Henley", stock: 3, fillRate: 49, status: "Out" },
  { sku: "SKU-1021", name: "Zip Hoodie", stock: 76, fillRate: 89, status: "Healthy" },
  { sku: "SKU-1022", name: "Travel Shirt", stock: 41, fillRate: 82, status: "Healthy" },
  { sku: "SKU-1023", name: "Rib Tank", stock: 19, fillRate: 73, status: "Risk" },
  { sku: "SKU-1024", name: "Coastal Shorts", stock: 33, fillRate: 85, status: "Healthy" },
  { sku: "SKU-1025", name: "Merino Crew", stock: 7, fillRate: 64, status: "Risk" },
  { sku: "SKU-1026", name: "Fleece Pullover", stock: 52, fillRate: 87, status: "Healthy" },
  { sku: "SKU-1027", name: "Classic Denim", stock: 11, fillRate: 66, status: "Risk" },
  { sku: "SKU-1028", name: "Linen Shirt", stock: 29, fillRate: 79, status: "Risk" },
  { sku: "SKU-1029", name: "Rugged Chino", stock: 61, fillRate: 88, status: "Healthy" },
  { sku: "SKU-1030", name: "City Backpack", stock: 5, fillRate: 58, status: "Out" },
  { sku: "SKU-1031", name: "Slim Tee", stock: 134, fillRate: 98, status: "Healthy" },
  { sku: "SKU-1032", name: "Cropped Crew", stock: 24, fillRate: 75, status: "Risk" },
  { sku: "SKU-1033", name: "Trail Jacket", stock: 14, fillRate: 70, status: "Risk" },
  { sku: "SKU-1034", name: "Windbreaker", stock: 38, fillRate: 83, status: "Healthy" },
  { sku: "SKU-1035", name: "Thermal Socks", stock: 182, fillRate: 96, status: "Healthy" },
  { sku: "SKU-1036", name: "Satin Blouse", stock: 2, fillRate: 47, status: "Out" },
  { sku: "SKU-1037", name: "Studio Shorts", stock: 21, fillRate: 74, status: "Risk" },
  { sku: "SKU-1038", name: "Workwear Pant", stock: 58, fillRate: 87, status: "Healthy" },
  { sku: "SKU-1039", name: "Canvas Tote", stock: 90, fillRate: 92, status: "Healthy" },
  { sku: "SKU-1040", name: "Rib Tee", stock: 16, fillRate: 72, status: "Risk" },
  { sku: "SKU-1041", name: "Padded Vest", stock: 9, fillRate: 62, status: "Risk" },
  { sku: "SKU-1042", name: "Softshell", stock: 26, fillRate: 78, status: "Risk" },
  { sku: "SKU-1043", name: "Hiking Pants", stock: 47, fillRate: 85, status: "Healthy" },
  { sku: "SKU-1044", name: "Canvas Cap", stock: 120, fillRate: 97, status: "Healthy" },
  { sku: "SKU-1045", name: "Tech Polo", stock: 30, fillRate: 80, status: "Risk" },
  { sku: "SKU-1046", name: "Rugby Shirt", stock: 13, fillRate: 69, status: "Risk" },
  { sku: "SKU-1047", name: "Wool Scarf", stock: 55, fillRate: 86, status: "Healthy" },
  { sku: "SKU-1048", name: "Thermal Tee", stock: 6, fillRate: 60, status: "Out" },
  { sku: "SKU-1049", name: "Light Chino", stock: 36, fillRate: 82, status: "Healthy" },
  { sku: "SKU-1050", name: "Studio Crew", stock: 28, fillRate: 79, status: "Risk" },
];
